### PR TITLE
Add 'instrument-functions' mixin

### PR DESCRIPTION
**Pull request by christophebedard**
To enable the [`-finstrument-functions` gcc option](https://gcc.gnu.org/onlinedocs/gcc-9.3.0/gcc/Instrumentation-Options.html#Instrumentation-Options).

Signed-off-by: Christophe Bedard <bedard.christophe@gmail.com>

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
@christophebedard do you think that `instrument` may be too generic a mixin name since there are other forms of build and test instrumentation and mixins for those may be added some day?

**Comment by christophebedard** [comment]
yeah, but my reasoning was that other instrumentation-related mixins could be added to this same file. I don't mind renaming the file though (to `instrument-functions.mixin`?).

**Comment by nuclearsandwich** [comment]
> a `.mixin` file name yeah, but my reasoning was that other instrumentation-related mixins could be added to this same file. I don't mind renaming the file though (to `instrument-functions.mixin`?).

I don't feel too strongly about it but figured I would ask. If you think there's room to include other instrumentation mixins in the file then let's leave it.

**Comment by christophebedard** [comment]
I just renamed it to `instrument-functions.mixin`.

**Review by nuclearsandwich — APPROVED** [review]

**Comment by nuclearsandwich** [comment]
Thanks for iterating!

**Pull request merged**
