### PR TITLE
Add rel-min-size build mixin for building with CMAKE_BUILD_TYPE=MinSizeRel

### PR DESCRIPTION
**Pull request by AAlon**
Related to https://github.com/colcon/colcon-cmake/issues/42

### CODE REVIEW

**Comment by dirk-thomas** [comment]
The proper build type is `MinSizeRel`, see https://cmake.org/cmake/help/v3.14/variable/CMAKE_BUILD_TYPE.html

Also make sure to insert the new mixin in alphabetical order to pass the tests (locally / on CI).

**Comment by dirk-thomas** [comment]
Please see my previous comment (`MinSizeRel`) and also match the mixin name with the correct build type name.

**Comment by AAlon** [comment]
Fixed

**Comment by dirk-thomas** [comment]
Still the wrong name.

**Comment by AAlon** [comment]
*facepalm* Now it's fixed.

**Pull request merged**
