### PR TITLE
Add a mixin for GCC coverage flags

### PR DESCRIPTION
**Pull request by jpsamper2009**
## How to use
1. Build
```bash
$ colcon build --mixin coverage
$ find ./build -name "*.gcno"
# a gcno for each source file that was built
$ rm $(find ./build -name "CMake*CompilerId.gcno")
# These are created by the CMake compiler checker
$ mkdir lcov
```

2. (Optional) Generate baseline zero-coverage using `lcov --initial ...`
```bash
$ lcov \
    --base-directory .  \
    --initial \
    --capture \
    --directory ./build \
    --output-file ./lcov/zero-coverage \
    --no-external \
    --rc lcov_branch_coverage=1
```

3. Run tests
```bash
$ colcon test
$ find ./build -name "*.gcda"
# a gcda for each source file whose code was executed
```

4. Use lcov to generate coverage output
```bash
$ lcov \
    --base-directory . \
    --capture \
    --directory ./build \
    --output-file lcov/coverage \
    --no-external \
    --rc lcov_branch_coverage=1
```

5. (optional) Combine zero-coverage (from step 2) with coverage output (from step 4)
```bash
$ lcov \
    --add-tracefile lcov/zero-coverage \
    --add-tracefile lcov/coverage \
    --output-file lcov/total_coverage \
    --rc lcov_branch_coverage=1
```

6. Use `genhtml` to generate browsable coverage information
```bash
$ genhtml \
    --output-directory ./lcov/html" \
    "./lcov/total_coverage" \
    --prefix . \
    --legend \
    --demangle-cpp \
    --rc genhtml_branch_coverage=1
```

7. Open the generate html: e.g.,
```bash
chromium-browser ./lcov/html/index.html
```

## Future Work
A `colcon coverage-results` command to wrap the `lcov` commands such that we can leverage the package selection extension of `colcon`?

cc @wjwwood 

## Reference
Close colcon/colcon-core#94

### CODE REVIEW

**Comment by jpsamper2009** [comment]
cc @dejanpan

**Comment by dirk-thomas** [comment]
Sorry, for the max line length hassle. That check came by default with `yamllint` and we didn't had longer lines until now. I lifted the restriction in #9.

I will edit the patch to keep the indentation at 4 spaces (like the other files) and change the order of the two arguments to be in alphabetical order. Afterwards this still needs to be rebased (to get the changes from #9 once it is merged).

**Comment by dirk-thomas** [comment]
Thinking about this a similar comment than https://github.com/colcon/colcon-mixin-repository/pull/7#issuecomment-419538524 applies here. The arguments for `coverage` are specific to `gcc`. Users with other compilers can't use the mixin like this. Maybe it would be better to rename the mixin to `coverage-gcc` (see https://github.com/colcon/colcon-mixin-repository/commit/1fa98fe3226feea27d48c6c4c70869e9db778ac2). That would allow to add `coverage-clang` etc. in the future. Does that sound reasonable?

**Comment by dirk-thomas** [comment]
> Does that sound reasonable?

I created a follow up PR for this: #10.

**Pull request merged**
