### PR TITLE
Remove non-standard `-DCOVERAGE_RUN=1`

### PR DESCRIPTION
**Pull request by mikaelarguedas**
@jpsamper2009 @dirk-thomas to give feedback

### CODE REVIEW

**Comment by dirk-thomas** [comment]
The patch looks good to me. I will leave it up to @jpsamper2009 to try / confirm.

**Comment by mikaelarguedas** [comment]
@jpsamper2009 (maybe obvious question) can you also confirm what the "COVERAGE_RUN" option does ?
Thanks!

**Comment by mikaelarguedas** [comment]
Thanks @jpsamper2009 for the quick feedback!

> The `COVERAGE_RUN` option is not strictly necessary, but it can be useful when tests need different parameters during the coverage run.

Is the name of that definition "standardized" anywhere? or is it a custom "arbitrary" definition?

I'm fine leaving it as is for now. Though if it is arbitrary, maybe it doesn't belong in the `mixin` as anyone using a different arbitrary definition will not have a use for this one (and potentially have "unused cli argument" warnings in their CMake invocations).

**Comment by jpsamper2009** [comment]
@mikaelarguedas Completely arbitrary :smile: I was surprised it got through the initial review hehe

Feel free to delete it

**Pull request merged**
