### PR TITLE
feat: add sccache mixin

### PR DESCRIPTION
**Pull request by hashb**
Adds a mixin for [sccache](https://github.com/mozilla/sccache)

### CODE REVIEW

**Comment by furushchev** [comment]
@nuclearsandwich I'm waiting for this cool PR to be merged. Is there anything that blocks to make it happen? Is there anything I can help you?

**Comment by furushchev** [comment]
@nuclearsandwich ping

**Comment by furushchev** [comment]
This PR has been open since March, and there is still no response from maintainers, yet it is such a simple change.
@cottsay @tylerjw Do you know how is the maintenance of the ROS2 / colcon project going on? (I mentioned since you're recent committers on this repo)

**Review by tylerjw — APPROVED** [review]
This looks like a good change. Thank you for the ping. I'll bring this up in the ROS meeting next week if it isn't merged by then.

**Comment by furushchev** [comment]
@tylerjw Thank you for the super quick response! 

> I'll bring this up in the ROS meeting next week if it isn't merged by then.

Do you mind if I ask what the meeting is? (If you have a link, it would be appreciated.)

**Comment by tylerjw** [comment]
It isn't public and I'm not fancy enough to invite people. I'm sorry.

**Pull request merged**
